server.port: 8081

---
spring:
  profiles: developers

myproperty1: value-from-developers-profile1
myproperty2: '{cipher}AQBjn+KYoKYYn+8XPkrMJuzZxSe9QxjfiFEDwb6Cl5OoA8b4pgZRK9kAIrPqdYj+3aU+FM/Few3dkHEzavHUjbw0cx9BTX4f9vZ3FaSn54SXu/7O1df7eb6JlyneoWANSitQGG8nejhrb7CEO8agSPIQPeHFANFsz6XRgVAxoRddkn4qBjMErrDi2HZbOTLyLDZOY0hlRvNUIqiz9T63H6g9dyFG7yrTIUH8AyVI3DJeC/dA2tcXiYeT6U3r19uLVO4BoU6pvS4bdo2KLXCsz2ww/uA/QaSVVLfXOOvpa8mQcNd9zVZvgBuVgPPjEM6okfLO9Pu0bFAscHVCtFm1aAyRnw23LJAUbxy8IM78MBQTnMGgBOzhJek6umUWlMw/mDS7+9GTnWN3BaYtuvkpvvsj'
myproperty3: '{cipher}AQA9pv0LGcsWSyn12pM250NEJmwnnshW84GXcCs9Nj9GNglopZaB1j+LEn5lR5I0oZiUT835yCoEBJzELRSvTQDQX96W502mef+ukZ7OeEd4ChchtF6OzWpkouZZEjON3Z04S4uus6HRXfFX2wABBHsLE0/vK8kpVVeWDJS5e3LfoyE3a0CsVeRTvdrqpOUjCXxNm5AnQzoMuEQotlt7+mYjJyEJsbysulik3m2cA11FljyMSYi8rICpDdUMDNjbm9VYuL0Mv5sGA1XygBLTvUgvQCeqrVw9KYssCI/T1Ey3zb971DjXWhx+2XXR47DEWsDNNnwgTm8Z/eZpf3YJjcxC/scGe3kjw1M5o6ZljVkkvcvfstnY3iEb9ZBkHLOsUpNPr6xnWeSBS3FXhPJ9B6fX'


