
myproperty1: value-from-local-profile1
myproperty2: value-from-local-profile2
myproperty3: '{cipher}AQAIEQwWNUFrwSKJ8a0ZPahQfP3sId3vWBIhM+Fy8LyCiUAFCwLc8arttca5LsjiVdOCRTQy5/ew/h0oLlwpoDCnSQZjPrRn/0lAkzAr0YnFkMD8xofsn+/NkfJB4fyQJm3zrE/CoYLPu70KooEy8ra7Lg+KQR+77OXoYs+DTePB5Q7g5nhGMcrdamEPPoRPSf+qHuUTLQo6HgY5f4Uo0E3qQV4ssuHaeZQT6DyuHSP7X7tKrq68c00sZE4aQEyZ1cY1By/kAxBVi+O2/bTOftDddCe56BtDp1iPa4w+SPpYbaMVtpjHxtJew3NM2T2sGFJTq38pljrElvAbDr/EWti8FbEXbQibF/MW02WXq8d5UkAnilt5QAZW41+vO+lu25X/9Sm3qHvtdNP4XsTfN+BL'

